apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-creds
  namespace: solar-system
type: Opaque
data:
 MONGO_URI: mongodb+srv://superuser:SuperPassword@supercluster.d83jj.mongodb.net/superData
 MONGO_USERNAME: superuser
 MONGO_PASSWORD: SuperPassword