apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  labels:
    app: solar-system-deploy
  namespace: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      name: solar-system
      labels:
        app: solar-system
    spec:
      containers:
        - name: solar-container
          image: chowdary2001/solar-system:999
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-db-creds
                  key: MONGO_URI
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-creds
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-creds
                  key: MONGO_PASSWORD
